#Configuation de notre API
spring:
  application:
    name: classe-service

  #Configuration de la base de données ici msql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classe-service
    username: root
    password: password

  #Configuration de JPA avec hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true

#COnfiguraiotn du port d'accès
server:
  port: 8080

#Pour la documentation du document - Utilisation de swagger
springdoc:
  api-docs:
    path: /api-docs
